services:
  mysql:
    container_name: mysql-login-app
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      MYSQL_DATABASE: login_app 
    ports:
      - "3306:3306"
    volumes:
      - login-app-mysql-volume:/var/lib/mysql
    networks:
      - login-app
    restart: always
  phpMyAdmin:
    container_name: phpmyadmin-login-app
    restart: always
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    networks:
      - login-app
    depends_on:
      - mysql
  mail-dev:
    container_name: mail-dev-login-app
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
networks: 
  login-app: 
    driver: bridge
volumes: 
  login-app-mysql-volume: 
    driver: local